#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
alpha:
  app: teamstrongpm-staging
  stack: cedar
  config:
    RACK_ENV: "alpha"
    RAILS_ENV: "alpha"
  addons:
    - heroku-postgresql:dev
    - memcachier:dev
    - newrelic:standard
    - redistogo:nano
    - pgbackups:plus
    - sendgrid:starter
    
production:
  app: teamstrongpm
  stack: cedar
  config:
    RACK_ENV: "production"
    RAILS_ENV: "production"
  addons:
    - heroku-postgresql:dev
    - pgbackups:auto-month
    - memcachier:dev
    - newrelic:standard
    - redistogo:nano
    - sendgrid:starter